// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Employee_CRUD.Models;

namespace Employee_CRUD.Data
{
    public partial class MaqtaContext : DbContext
    {
        public MaqtaContext()
        {
        }

        public MaqtaContext(DbContextOptions<MaqtaContext> options)
            : base(options)
        {
        }

       
    }
}